version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: subscription
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/subscription
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 111
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: